// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVhSjdfT-AF8uM4WEiyNTWesilfvS_3Tc',
    appId: '1:908139891089:web:ef38445767817aef96f230',
    messagingSenderId: '908139891089',
    projectId: 'my-msg-df2f2',
    authDomain: 'my-msg-df2f2.firebaseapp.com',
    storageBucket: 'my-msg-df2f2.appspot.com',
    measurementId: 'G-7DXXBHPKE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNurh_xSfP0W8sgscDWcjpFAsx9p8dUHE',
    appId: '1:908139891089:android:62a4dce487e8545396f230',
    messagingSenderId: '908139891089',
    projectId: 'my-msg-df2f2',
    storageBucket: 'my-msg-df2f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFFXqAn8aG2sJ1igOalFCjOhPPDjTBaqY',
    appId: '1:908139891089:ios:f5943f2d622a273f96f230',
    messagingSenderId: '908139891089',
    projectId: 'my-msg-df2f2',
    storageBucket: 'my-msg-df2f2.appspot.com',
    iosBundleId: 'com.example.appMsg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFFXqAn8aG2sJ1igOalFCjOhPPDjTBaqY',
    appId: '1:908139891089:ios:91abbf6a440601f996f230',
    messagingSenderId: '908139891089',
    projectId: 'my-msg-df2f2',
    storageBucket: 'my-msg-df2f2.appspot.com',
    iosBundleId: 'com.example.appMsg.RunnerTests',
  );
}
